[platformio]
default_envs = pico

[env:pico]
platform = raspberrypi
board = pico
framework = arduino
monitor_speed = 115200
build_flags =
  -DNODE_ID=1
  -DPIO_FRAMEWORK_ARDUINO_ENABLE_EXCEPTIONS=0

[env:native_test]
platform = native
test_framework = unity
build_flags = -std=gnu++17
build_src_filter = +<protocol.cpp> -<main.cpp>
